### ISSUE TITLE
I think $NODE_IP replacement needs a more detailed explanation? 

### ISSUE THREAD

**Issue by pavanbelagatti** [kameshsampath/drone-java-quickstart#3]
I am a beginner and I got stuck at this point so thought I should add this. Why we did $NODE_IP replacement in the ~/.kube/config file is still hard to understand. (Anyways Kamesh explained me but I don't know about the users who try out this project for the first time)

**Comment by kameshsampath** [comment]
Closed via #b05a497654faff6bd9f066072279dd3ebd34ae33
